integralfamilies:
  - name: F15
    loop_momenta: [k1, k2, k3]
    propagators:
     - [ k1, 0 ]
     - [ k2, 0 ]
     - [ k3, 0 ]
     - [ p1-k1, 0 ]
     - [ p2+k1, 0 ]
     - [ p1-k1-k2, 0 ]
     - [ p2+k1+k2, 0 ]
     - [ p1-k1-k2-k3, 0 ]
     - [ p2+k1+k2+k3, 0 ]
     - [ p2+k2, 0 ]
     - [ p2+k2+k3, 0 ]
     - [ k2+k3, 0 ]
  - name: F6
    loop_momenta: [k1, k2, k3]
    propagators:
     - [ k1, 0 ]
     - [ k2, 0 ]
     - [ k3, 0 ]
     - [ p1-k1, 0 ]
     - [ k2+k3, 0 ]
     - [ p1-k1-k2, 0 ]
     - [ p2+k1+k2, 0 ]
     - [ p1-k1-k2-k3, 0 ]
     - [ p2+k1+k2+k3, 0 ]
     - [ p2+k2, 0 ]
     - [ p2+k2+k3, 0 ]
     - [ p1+p2-k1, 0 ]
  - name: F9
    loop_momenta: [k1, k2, k3]
    propagators:
     - [ k1, 0 ]
     - [ k2, 0 ]
     - [ k3, 0 ]
     - [ p1-k1, 0 ]
     - [ p2+k1, 0 ]
     - [ p1-k1-k2, 0 ]
     - [ p2+k1+k2, 0 ]
     - [ p1-k1-k2-k3, 0 ]
     - [ p2+k1+k2+k3, 0 ]
     - [ p2+k2, 0 ]
     - [ p2+k1+k3, 0 ]
     - [ k1+k3, 0 ]
  - name: F2
    loop_momenta: [k1, k2, k3]
    propagators:
     - [ k1, 0 ]
     - [ k2, 0 ]
     - [ k3, 0 ]
     - [ p1-k1, 0 ]
     - [ p1-k1-k2, 0 ]
     - [ p2+k1+k2, 0 ]
     - [ p2+k1-k3, 0 ]
     - [ k1-k3, 0 ]
     - [ k2+k3, 0 ]
     - [ k1+k2, 0 ]
     - [ p1-k1-k2-k3, 0 ]
     - [ p2+k3, 0 ]
  - name: F38
    loop_momenta: [k1, k2, k3]
    propagators:
     - [ k1, 0 ]
     - [ k2, 0 ]
     - [ k3, 0 ]
     - [ p1-k1, 0 ]
     - [ p2+k1, 0 ]
     - [ p1-k1-k2, 0 ]
     - [ p2+k1+k3, 0 ]
     - [ p1-k1-k2-k3, 0 ]
     - [ p2+k1+k2+k3, 0 ]
     - [ k2+k3, 0 ]
     - [ k1+k3, 0 ]
     - [ k1+k2, 0 ]
  - name: F4
    loop_momenta: [k1, k2, k3]
    propagators:
     - [ k1, 0 ]
     - [ k2, 0 ]
     - [ k3, 0 ]
     - [ p1-k1, 0 ]
     - [ p2+k2, 0 ]
     - [ p1-k1-k2, 0 ]
     - [ p2+k1+k2, 0 ]
     - [ p1-k1-k2-k3, 0 ]
     - [ p2+k1+k2+k3, 0 ]
     - [ k1+k2, 0 ]
     - [ k2+k3, 0 ]
     - [ p2+k3, 0 ]
