(* ::Package:: *)

(* ::Input:: *)
(*FeynmanDiagramGraph[expr_]:=Module[{edges,keys,ps,vertices,incid,ExtractPropagators,MomentumConservingQ,FindVertices},(*Define ExtractPropagators*)ExtractPropagators[expre_]:=Module[{denoms},denoms=Denominator[Together[expre]];*)
(*List@@denoms/. {Power[x_,2]:>x,Power[x_,4]:>x}];*)
(**)
(*(*Extract propagators (edges)*)*)
(*edges=ExtractPropagators[expr];*)
(*(*Extract momentum labels*)*)
(*keys=Cases[edges,s_Symbol/;StringMatchQ[SymbolName[s],"k"~~__]:>s,{0,Infinity}]//DeleteDuplicates;*)
(*ps=Cases[edges,s_Symbol/;StringMatchQ[SymbolName[s],"p"~~__]:>s,{0,Infinity}]//DeleteDuplicates;*)
(**)
(*(*Define MomentumConservingQ*)*)
(*MomentumConservingQ[subset_List]:=Simplify[Total[subset]===0];*)
(*(*Define FindVertices*)*)
(**)
(*FindVertices[edgers_List]:=Module[{vertics={}},Do[If[Length[s]>=3&&!SubsetQ[s,{p1,-p2,-p1+p2}]&&MomentumConservingQ[s]&&!AnyTrue[vertics,SubsetQ[s,#]&]&&!AnyTrue[s,MemberQ[s,-#]&],AppendTo[vertics,s]],{s,SortBy[Subsets[edgers,{3,Length[edgers]}],Length]}];*)
(*vertics];*)
(**)
(*(*Find vertices*)vertices=((Select[(FindVertices[Union[edges,-edges,{p1,-p2,-p1+p2}]]//Subsets[#,{Length[edges]-Length[keys]+1}]&),Sort[Flatten[#]]==Sort[Union[edges,-edges,{p1,-p2,-p1+p2}]]&]//Abs//Simplify)/. Abs[x_]:>x);*)
(*(*Build incidence list*)*)
(*incid=Table[Flatten[Table[ConstantArray[i->j,Length[Intersection[Union[vertices[[q]],{{p1},{p2},{p1-p2}}][[i]],Union[vertices[[q]],{{p1},{p2},{p1-p2}}][[j]]]]],{i,1,Length[Union[vertices[[q]],{{p1},{p2},{p1-p2}}]]},{j,i+1,Length[Union[vertices[[q]],{{p1},{p2},{p1-p2}}]]}]],{q,Length[vertices]}];*)
(**)
(*(*Plot the graph*)*)
(*Pick[GraphPlot[#]&/@incid,WeaklyConnectedGraphQ/@Graph/@incid]//First*)
(*]*)


(* ::Input:: *)
(*ProcessFeynmanDiagrams[F1_,Mappings_,opts___]:=Module[{AF1,Rats1,Coeff1,MIs1,GR1,RatGR1s,FFF1},(*Apply mappings and set r->1*)AF1=F1/. Mappings/. {r->1};*)
(*(*Extract rational parts*)Rats1=ExtractRationalParts[AF1];*)
(*(*Extract coefficients*)Coeff1=ExtractCoefficients[AF1,Rats1];*)
(*(*Get unique master integrals*)MIs1=Rats1//DeleteDuplicates;*)
(*(*Convert to Feynman diagram graphs*)GR1=FeynmanDiagramGraph/@MIs1;*)
(*(*Map rationals to graph symbols*)RatGR1s=MapRationalsToGraphSymbols[Rats1,MIs1,GR1];*)
(*(*Collect and simplify*)FFF1=CollectGraphCoefficients[Coeff1,RatGR1s,MIs1,GR1];*)
(*FFF1]*)
(**)
(*(*Helper function:Extract rational parts from denominators*)*)
(*ExtractRationalParts[expr_]:=Times@@(1/Select[List@@Denominator[#]/. {d->4,p2->-p2},!NumberQ[#]&])&/@(List@@Expand[expr])*)
(**)
(*(*Helper function:Extract coefficients*)*)
(*ExtractCoefficients[expr_,rats_]:=(List@@Expand[expr]/. {p2->-p2})/rats*)
(**)
(*(*Helper function:Map rationals to graph symbols*)*)
(*MapRationalsToGraphSymbols[rats_,MIs_,graphs_]:=Table[If[Thread[MIs->Array[GR1sub,Length[MIs]]][[i]][[1]]===rats[[j]],rats[[j]]/. Thread[MIs->Array[GR1sub,Length[MIs]]][[i]],0],{j,Length[rats]},{i,Length[MIs]}]//Flatten//DeleteCases[#,0]&*)
(**)
(*(*Helper function:Collect graph coefficients*)*)
(*CollectGraphCoefficients[coeff_,ratGRs_,MIs_,graphs_]:=(((coeff*ratGRs//Total)//FullSimplify)//Collect[#,Array[GR1sub,Length[MIs]]]&)/. Thread[Array[GR1sub,Length[MIs]]->graphs]*)
